import Head from "next/head";
import React from "react";
import Image from "next/image";

import Logo from "../components/layout/logo/Logo";
import Navbar from "../components/layout/Navbar";

import { IMenu } from "../types";
import Link from "next/link";

const menuData: IMenu[] = [
  { id: 1, title: "Home", slug: "" },
  { id: 2, title: "Gallery", slug: "gallery" },
  { id: 3, title: "Prices for services", slug: "prices" },
  { id: 4, title: "About us", slug: "about" },
  { id: 5, title: "Contact", slug: "contact" },
];

const Home = () => {
  const [isInit, setIsInit] = React.useState(false);
  const [isBurgerActive, setIsBurgerActive] = React.useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
      </Head>
      <main>
        <div
          style={{
            background: `#222021 url("https://res.cloudinary.com/zielona-g-ra/image/upload/v1662633724/wood/bg-vector_j8r9lo.svg") repeat-y  center / cover`,
            width: "100%",
          }}
          className='wrapper relative'
        >
          <div
            className='header__bg-image'
            style={{
              background: ` url("https://res.cloudinary.com/zielona-g-ra/image/upload/v1661867072/wood/logs_hk9ana.webp") no-repeat  center / cover`,
              opacity: "0.5",
              boxShadow: "2px 2px 30px rgba(34, 32, 33, 0.76)",
            }}
          ></div>

          <div
            style={{ borderTopRightRadius: "42px" }}
            className={
              isInit
                ? isBurgerActive
                  ? "mobile-close fixed top-40 left-0 right-40 bottom-0 z-50 h-full bg-white py-10 flex justify-center uppercase "
                  : "mobile-open fixed top-40 left-0 right-20 bottom-0 z-50 h-full bg-white py-10 flex justify-center uppercase "
                : "mobile-init fixed top-40 left-0 right-40 bottom-0 z-50 h-full bg-white py-10 flex justify-center uppercase "
            }
          >
            <Navbar
              closeMobilePanel={() => {
                setIsBurgerActive(false);
              }}
              menuData={menuData}
              ulStyles='flex flex-col  gap-y-10  bg-white text-black px-4'
              liStyles='text-3xl'
            />
          </div>

          <div className='fixed w-full  top-12 z-50 flex justify-between items-center px-4 md:px-10 xl:px-20'>
            <div className='header__logo'>
              <Logo />
            </div>
            <div className='header__navbar  hidden lg:block '>
              <Navbar
                menuData={menuData}
                ulStyles='flex flex-wrap gap-x-16 xl:gap-x-30 2xl:gap-x-40  text-xl ml-10 '
                liStyles='hover:opacity-50'
              />
            </div>
            <div
              className='burger  lg:hidden'
              onClick={() => {
                setIsInit(true);
                setIsBurgerActive((s) => !s);
              }}
            >
              <div
                className={
                  isBurgerActive
                    ? "burger__top-line"
                    : "burger__top-line--short"
                }
              ></div>
              <div className={"burger__mid-line"}></div>
              <div
                className={
                  isBurgerActive
                    ? "burger__bottom-line"
                    : "burger__top-bottom--short"
                }
              ></div>
            </div>
          </div>
          <div style={{ height: "100vh" }}>
            <div className='absolute top-44 left-0 right-0 mx-auto'>
              <div className='relative  text-center px-4'>
                <Image src={"/404.svg"} width={1096} height={539} alt='' />
              </div>
              <div className='flex flex-col justify-center'>
                <h1 className='header_title text-center'>Woops</h1>
                <p className='text-xl lg:text-3xl text-center mt-4'>
                  Oh, you must be lost, there is no such page.
                </p>
                <button className='mt-16'>
                  <Link href='/'>
                    <a className='mybtn'>Go to the home page</a>
                  </Link>
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
