import Head from "next/head";
import React from "react";
import Image from "next/image";
import { ICard, IMenu, ISlide } from "../types";
import Footer from "../components/layout/Footer";
import MobileMenu from "../components/ui/MobileMenu";
import Menu from "../components/ui/Menu";

export const getServerSideProps = async () => {
  const menuData: IMenu[] = [
    { id: 1, title: "Home", slug: "" },
    { id: 2, title: "Gallery", slug: "gallery" },
    { id: 3, title: "Prices for services", slug: "prices" },
    { id: 4, title: "About us", slug: "about" },
    { id: 5, title: "Contact", slug: "contact" },
  ];

  return {
    props: {
      menuData,
    },
  };
};

const Home = ({
  menuData,
}: {
  data: string;
  menuData: IMenu[];
  cards: ICard[];
  slides: ISlide[];
}) => {
  const [isInit, setIsInit] = React.useState(false);
  const [isBurgerActive, setIsBurgerActive] = React.useState(true);
  const burgerHandler = () => {
    setIsBurgerActive((s) => !s);
  };

  const offBurger = () => {
    if (!isBurgerActive) {
      setIsBurgerActive(true);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
      </Head>
      <main>
        <div
          style={{
            background: `#222021 url("https://res.cloudinary.com/zielona-g-ra/image/upload/v1662633724/wood/bg-vector_j8r9lo.svg") repeat-y  center / cover`,
            width: "100%",
          }}
          className='relative'
        >
          <MobileMenu
            isInit={isInit}
            isBurgerActive={isBurgerActive}
            setIsBurgerActive={setIsBurgerActive}
            menuData={menuData}
          />

          <Menu
            menuData={menuData}
            setIsInit={setIsInit}
            burgerHandler={burgerHandler}
            isBurgerActive={isBurgerActive}
          />

          <section
            onClick={offBurger}
            className={`${
              isBurgerActive ? "blur-none" : "blur "
            } w-full lg:w-4/6 lg:mx-auto pt-40 lg:pt-96`}
            style={{ paddingBottom: "400px", minHeight: "100vh" }}
          >
            <div className='flex flex-col lg:flex-row justify-center items-center'>
              <div className='lg:basis-1/2'>
                <h1 className='contact_page header uppercase barrio'>
                  Contact
                </h1>
                <div className='flex items-center mt-10 lg:mt-36 '>
                  <Image
                    src='/ph_phone-call.svg'
                    alt='phone'
                    width={50}
                    height={50}
                  />
                  <p className='text-xl lg:text-3xl'>+420 000 000 000</p>
                </div>
                <div className='mt-4 lg:mt-8  flex items-center'>
                  <Image
                    src='/adress.svg'
                    alt='adress'
                    width={50}
                    height={50}
                  />
                  <p className='text-xl lg:text-3xl'>
                    Na Plzeňce 1166/0 150 00
                  </p>
                </div>
              </div>
              <div>
                <div className='lg:basis-1/2 text-center my-10'>
                  <iframe
                    className='contact_page map'
                    src='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2806.8245438441622!2d24.937286383404366!3d60.16873679806441!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46920bccb7ab4601%3A0x5b903f6a66114674!2sGlaspalatstorget%2C%20Lasipalatsinaukio%2C%2000100%20Helsinki%2C%20Finlandia!5e0!3m2!1spl!2spl!4v1662708465547!5m2!1spl!2spl'
                    allowFullScreen={true}
                    loading='lazy'
                    referrerPolicy='no-referrer-when-downgrade'
                  ></iframe>
                </div>
              </div>
            </div>
          </section>

          <Footer />
        </div>
      </main>
    </>
  );
};

export default Home;
