import Head from "next/head";
import React from "react";
import Image from "next/image";
import Contact from "../components/Contact";
import Footer from "../components/layout/Footer";
import Menu from "../components/ui/Menu";
import MobileMenu from "../components/ui/MobileMenu";

import { ICard, IMenu, ISlide } from "../types";

export const getServerSideProps = async () => {
  const data = "Hello world!!! Test!!!";

  const menuData: IMenu[] = [
    { id: 1, title: "Home", slug: "" },
    { id: 2, title: "Gallery", slug: "gallery" },
    { id: 3, title: "Prices for services", slug: "prices" },
    { id: 4, title: "About us", slug: "about" },
    { id: 5, title: "Contact", slug: "contact" },
  ];

  const cards: ICard[] = [
    {
      id: 1,
      image_src:
        "https://res.cloudinary.com/zielona-g-ra/image/upload/v1662019486/wood/old-wood-grain-background-3_sqsfkb.webp",
      title: "Oak",
      description: [
        { option: "Durability", isTrue: true },
        { option: "Beautiful texture", isTrue: true },
        { option: "Water resistance", isTrue: true },
        { option: "Expensive", isTrue: false },
      ],
    },
    {
      id: 2,
      image_src:
        "https://res.cloudinary.com/zielona-g-ra/image/upload/v1662019486/wood/wood-texture-design-decoration-2_c5tnh6.webp",
      title: "Buk",
      description: [
        { option: "Durability", isTrue: true },
        { option: "Hard to handle", isTrue: false },
      ],
    },
    {
      id: 3,
      image_src:
        "https://res.cloudinary.com/zielona-g-ra/image/upload/v1662019486/wood/pale-oak-wood-texture-design-background-2_hhwbjb.webp",
      title: "Ash",
      description: [
        { option: "Durability", isTrue: true },
        { option: "Hard to handle", isTrue: false },
      ],
    },
  ];

  const slides = [
    {
      id: 1,
      src: "https://res.cloudinary.com/zielona-g-ra/image/upload/v1662034122/wood/modern-wooden-kitchen-interior-steel-kitchen-faucet-3_sg4cwg.webp",
    },
    {
      id: 2,
      src: "https://res.cloudinary.com/zielona-g-ra/image/upload/v1662110981/wood/lucas-hoang-oujKSaZlMFY-unsplash-1_ghhrav.webp",
    },
    {
      id: 3,
      src: "https://res.cloudinary.com/zielona-g-ra/image/upload/v1662110974/wood/ehud-neuhaus-iv77yw43cAI-unsplash-1_bqlkqo.webp",
    },
  ];

  return {
    props: {
      menuData,
      slides,
    },
  };
};

const PriceModal = ({ closeModal }: { closeModal(): void }) => {
  return (
    <div className='modal'>
      <div className='relative modal__img'>
        <Image
          alt=''
          src={
            "https://res.cloudinary.com/zielona-g-ra/image/upload/v1662960351/wood/Slice_1_2_c0ilo8.png"
          }
          // style={{ overflow: "scroll" }}
          layout='fill'
        />
      </div>
      <div onClick={closeModal} className='modal__close'>
        CLOSE
      </div>
    </div>
  );
};

const Home = ({
  menuData,
  slides,
}: {
  data: string;
  menuData: IMenu[];
  cards: ICard[];
  slides: ISlide[];
}) => {
  const [isInit, setIsInit] = React.useState(false);
  const [isBurgerActive, setIsBurgerActive] = React.useState(true);
  const [isModal, setIsModal] = React.useState(false);

  const burgerHandler = () => {
    setIsBurgerActive((s) => !s);
  };

  const openModal = () => {
    setIsModal(true);
  };

  const closeModal = () => {
    setIsModal(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
      </Head>
      <main>
        {isModal && <PriceModal closeModal={closeModal} />}
        <div
          style={{
            background: `#222021 url("https://res.cloudinary.com/zielona-g-ra/image/upload/v1662633724/wood/bg-vector_j8r9lo.svg") repeat-y  center / cover`,
            width: "100%",
          }}
          className='relative'
        >
          <MobileMenu
            isInit={isInit}
            isBurgerActive={isBurgerActive}
            setIsBurgerActive={setIsBurgerActive}
            menuData={menuData}
          />

          <Menu
            menuData={menuData}
            setIsInit={setIsInit}
            burgerHandler={burgerHandler}
            isBurgerActive={isBurgerActive}
          />
          <div className='w-5/6 mx-auto pt-20 lg:pt-72'>
            <div className='relative priceslist  mx-auto '>
              <Image
                alt=''
                layout='fill'
                src={
                  "https://res.cloudinary.com/zielona-g-ra/image/upload/v1662717666/wood/Prices_roe7n8.webp"
                }
                style={{ borderRadius: "42px" }}
                onClick={openModal}
                className='pt-20'
              />
            </div>
          </div>
          <Contact />

          <Footer />
        </div>
      </main>
    </>
  );
};

export default Home;
